compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  gradient_clipping: 2.0
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero_stage: 1
  activation_checkpointing:
    partition_activations: true
    contiguous_memory_optimization: true
    cpu_checkpointing: false
    number_checkpoints: null
    synchronize_checkpoint_boundary: false
    profile: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
main_training_function: main
mixed_precision: bf16
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
